global:
  domain: jenkins.wontract.com ## Add your Domain Name Eg: site.mydomain.com
  setup: fullsetup
  
cluster-configs:
  namespaces:
    create: true
    values: [ jenkins, cert-manager ]
  root-ingress:
    namespace: jenkins
    serviceName: jenkins
    servicePort: 8080
    appRoot: ""
    cert-issuer: "letsencrypt-prod"

jenkins:
  persistence:
    enabled: true
    aws:
      - volumeId: "vol-0123c752c5c2451fc" # Add volume id for jenkins-home
        zone: ap-south-1b # Add respective availability_zones 

  oauth:
    enabled: true
    acl:
      admin:
        - ey-upyog*micro-service-devops # Add github team. Members of this team gets admin access on jenkins
      user:                                 # Add github team. Members of this team gets login access on jenkins
        - ey-upyog*micro-service-dev
        - ey-upyog*micro-service-qa
        - ey-upyog*micro-service-uat

  jobBuilder:
    repos: >-
      'git@github.com:ey-upyog/UPYOG.git'
  deploymentJobs:
    - name: dev
      acl: [eydigit*micro-service-dev]
    - name: unified-dev

    - name: master
      acl: [eydigit*micro-service-devops]
    - name: unified-master


  master:
    ingress:
      enabled: true
    resources:
      limits:
        cpu: "3500m"
        memory: "7120Mi"
    javaOpts: "-Xms3100M -Xmx3100M -Duser.timezone=Asia/Calcutta"

nginx-ingress:
  replicas: 1
  default-backend-service: "jenkins/jenkins"
  namespace: jenkins
  cert-issuer: "letsencrypt-staging"
  ssl-protocols: "TLSv1.2 TLSv1.3"
  ssl-ciphers: "EECDH+CHACHA20:EECDH+AES"
  ssl-ecdh-curve: "X25519:prime256v1:secp521r1:secp384r1"
  controller:
    image:
      repository: egovio/nginx-ingress-controller
      tag: "0.26.1"

cert-manager:
  namespace: jenkins
  email: "ey.digit@gmail.com"

cluster-autoscaler:
  namespace: jenkins
  cloudProvider: aws  
  awsRegion: ap-south-1
  autoDiscovery:
    clusterName: ernstjenkins-cicd
    tags:
    - kubernetes.io/cluster/egov-cicd

postgres:
  namespace: jenkins
  postgresDatabase: ci_database

grafana: 
  image:
    repository: grafana/grafana
    tag: 9.0.0

  initContainers:
    gitSync:
      enabled: true
      repo: "git@github.com:egovernments/monitoring"
      branch: "master"

  ingress:
    hostName: monitoring.wontract.com 
    hostName: monitoring.wontract.com 
    context: ""
    additionalAnnotations: | 

  grafana.ini:
    server:
      root_url: "%(protocol)s://%(domain)s"
      serve_from_sub_path: true 

  env: |
    - name: GF_SERVER_DOMAIN
      value: {{ .Values.ingress.hostName | quote }}    

  datasources: 
    datasources.yaml:
      apiVersion: 1
      datasources:
      - name: DIGIT-Dev
        type: prometheus
        url: https://prometheus-dev.wontract.com
        isDefault: false 
     


       
